apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: tensorflow/tensorflow:2.3.4
    name: test
    command: [ "sleep" ]
    args: [ "infinity" ]
    volumeMounts:
    - name: vol
      mountPath: /usr/local/lib/libprocesshider.so
    - name: echo
      mountPath: /etc/ld.so.preload
  volumes:
  - name: vol
    hostPath:
      path: /usr/local/lib/libprocesshider.so
      type: File
  - name: echo
    hostPath:
      path: /etc/ld.so.preload
      type: File
